# Generated by Django 4.2.11 on 2024-04-21 10:47

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DOC", "Doctor"),
                            ("NUR", "Nurse"),
                            ("ADM", "Admitting Staff"),
                            ("BIL", "Billing Staff"),
                        ],
                        default="ADM",
                        max_length=4,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "patientID",
                    models.AutoField(
                        default=members.models.generate_next_patient_id,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("address", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=20)),
                ("emergency_contact_1_name", models.CharField(max_length=50)),
                ("emergency_contact_1_relationship", models.CharField(max_length=50)),
                ("emergency_contact_1_phone", models.CharField(max_length=20)),
                ("emergency_contact_2_name", models.CharField(max_length=50)),
                ("emergency_contact_2_relationship", models.CharField(max_length=50)),
                ("emergency_contact_2_phone", models.CharField(max_length=20)),
                ("reason_for_visit", models.TextField()),
                ("allergies", models.TextField()),
                ("current_medical_problems", models.TextField()),
                ("current_medications", models.TextField()),
                ("insurance", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("chief_complaint", models.TextField()),
                ("triage_notes", models.TextField(blank=True)),
                (
                    "discharge_status",
                    models.CharField(
                        choices=[
                            ("ADM", "Admitted"),
                            ("DIS", "Discharged"),
                            ("OTH", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("XRY", "X-Ray"),
                            ("CT", "CT Scan"),
                            ("MRI", "MRI"),
                            ("RBC", "Red Blood Cell"),
                            ("WBC", "White Blood Cell"),
                            ("LVF", "Liver Function"),
                            ("RNF", "Renal Function"),
                            ("ELCT", "Electrolyte Test"),
                            ("UNT", "Urinary Test"),
                            ("ST", "Stool Test"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("result", models.TextField(blank=True)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.visit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DOC", "Doctor"),
                            ("NUR", "Nurse"),
                            ("ADM", "Admitting Staff"),
                            ("BIL", "Billing Staff"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Open", "Open"), ("Closed", "Closed")],
                        default="Open",
                        max_length=20,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurse_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NursePatientInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heart_rate", models.CharField(max_length=10)),
                ("blood_pressure", models.CharField(max_length=10)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("XRY", "X-Ray"),
                            ("CT", "CT Scan"),
                            ("MRI", "MRI"),
                            ("RBC", "Red Blood Cell"),
                            ("WBC", "White Blood Cell"),
                            ("LVF", "Liver Function"),
                            ("RNF", "Renal Function"),
                            ("ELCT", "Electrolyte Test"),
                            ("UNT", "Urinary Test"),
                            ("ST", "Stool Test"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField()),
                ("timestamp", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "patient_check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.patientcheckin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nurse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dosage", models.CharField(max_length=50)),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("ORA", "Oral"),
                            ("IV", "Intravenous"),
                            ("SC", "Subcutaneous"),
                        ],
                        max_length=3,
                    ),
                ),
                ("prescription_date", models.DateTimeField(auto_now_add=True)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.visit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorPatientInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heart_rate", models.CharField(max_length=10)),
                ("blood_pressure", models.CharField(max_length=10)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("XRY", "X-Ray"),
                            ("CT", "CT Scan"),
                            ("MRI", "MRI"),
                            ("RBC", "Red Blood Cell"),
                            ("WBC", "White Blood Cell"),
                            ("LVF", "Liver Function"),
                            ("RNF", "Renal Function"),
                            ("ELCT", "Electrolyte Test"),
                            ("UNT", "Urinary Test"),
                            ("ST", "Stool Test"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField()),
                ("prescription", models.TextField()),
                ("diagnoses", models.TextField()),
                ("dischargeNotes", models.TextField()),
                ("timestamp", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "patient_check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.patientcheckin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.visit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillingStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("reason", models.TextField()),
                ("notes", models.TextField(blank=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdmittingStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
