# Generated by Django 4.2.11 on 2024-04-25 12:06

from django.db import migrations

def add_testtype_data(apps, schema_editor):
    TestType = apps.get_model('members', 'TestType')
    test_types = [
        TestType(name='Red Blood Cell', description='Hematologic laboratory test for red blood cell count'),
        TestType(name='White Blood Cell', description='Hematologic laboratory test for white blood cell count'),
        TestType(name='Liver Function Test', description='Hematologic laboratory test for liver function'),
        TestType(name='Renal Function Test', description='Hematologic laboratory test for kidney function'),
        TestType(name='Electrolyte Test', description='Hematologic laboratory test for electrolyte levels'),
        TestType(name='X-Ray', description='Radiographic test'),
        TestType(name='CT Scan', description='Computed Tomography'),
        TestType(name='MRI', description='Magnetic Resonance Imaging'),
        TestType(name='Urinary Test', description='Analysis of urine for medical diagnosis'),
        TestType(name='Stool Test', description='Analysis of stool for medical diagnosis')
    ]
    TestType.objects.bulk_create(test_types)

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_testtype_data),
    ]
